blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/anivar/termbrain/discussions/categories/q-a
    about: Please ask and answer questions in GitHub Discussions
  - name: Show and Tell
    url: https://github.com/anivar/termbrain/discussions/categories/show-and-tell
    about: Share your Termbrain workflows and use cases
  - name: Documentation
    url: https://github.com/anivar/termbrain/tree/main/docs
    about: Check if your question is answered in the docs