#!/usr/bin/env bash
# Claude AI provider for Termbrain

tb::claude_export() {
    local context_file="${1:-.claude.md}"
    local query="${2:-general}"
    
    {
        echo "# Claude Context"
        echo ""
        echo "This context was generated by Termbrain for use with Claude."
        echo ""
        
        # Include standard context
        tb::ai "$query" > /tmp/tb-claude-temp.md
        cat /tmp/tb-claude-temp.md
        rm -f /tmp/tb-claude-temp.md
        
        echo ""
        echo "## Claude-Specific Notes"
        echo ""
        echo "- Use this context to understand my development environment"
        echo "- Pay attention to recent errors and their solutions"
        echo "- Consider the patterns in my workflow"
        
    } > "$context_file"
    
    echo "📝 Claude context saved to $context_file"
}